### ISSUE TITLE
error while parsing static get = 1

### ISSUE THREAD

**Issue by LongTengDao** [acornjs/acorn-static-class-features#2]
```js
'use strict';

Error.stackTraceLimit = 100;

const parser = require('acorn').Parser.extend(require('acorn-stage3'));

parser.parse(` class a { static 'get' = 1; } `);// avoid error

parser.parse(` class a { static get = 1; } `);// error but valid in fact

```

```toml
stack = """
SyntaxError: Unexpected token (1:22)
    at Object.pp$4.raise (/node_modules/acorn/dist/acorn.js:2828:15)
    at Object.pp.unexpected (/node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp$3.parseIdent (/node_modules/acorn/dist/acorn.js:2779:12)
    at Object.parseIdent (/node_modules/acorn-stage3/node_modules/acorn-class-fields/index.js:54:27)
    at Object.parseIdent (/node_modules/acorn-stage3/node_modules/acorn-static-class-features/index.js:121:27)
    at Object.pp$3.parsePropertyName (/node_modules/acorn/dist/acorn.js:2584:107)
    at Object.parsePropertyName (/node_modules/acorn-stage3/node_modules/acorn-private-methods/index.js:21:36)
    at Object.parseClassElement (/node_modules/acorn-stage3/node_modules/acorn-static-class-features/index.js:83:14)
    at Object.parseClassElement (/node_modules/acorn-stage3/node_modules/acorn-private-methods/index.js:13:46)
    at Object.pp$1.parseClass (/node_modules/acorn/dist/acorn.js:1317:26)
    at Object.parseClass (/node_modules/acorn-stage3/node_modules/acorn-private-class-elements/index.js:78:29)
    at Object.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:835:19)
    at Object.parseStatement (/node_modules/acorn-stage3/node_modules/acorn-import-meta/index.js:38:22)
    at Object.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/node_modules/acorn/dist/acorn.js:576:37)
    at Object.<anonymous> (/TEST.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11"""

message = "Unexpected token (1:22)"

pos = 22

loc.line = 1

loc.column = 22

raisedAt = 23
```

https://github.com/acornjs/acorn/issues/852

**Comment by LongTengDao** [comment]
https://github.com/acornjs/acorn-static-class-features/issues/1

**Comment by adrianheine** [comment]
works with 0.2.1.
